import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = process.argv[2] === "production";
const vaultPluginDir = "D:/Data/Documents/lixinye/.obsidian/plugins/decision-tagger";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	// Copy to vault plugin directory
	if (!fs.existsSync(vaultPluginDir)) {
		fs.mkdirSync(vaultPluginDir, { recursive: true });
	}
	fs.copyFileSync("main.js", path.join(vaultPluginDir, "main.js"));
	if (fs.existsSync("manifest.json")) {
		fs.copyFileSync("manifest.json", path.join(vaultPluginDir, "manifest.json"));
	}
	if (fs.existsSync("styles.css")) {
		fs.copyFileSync("styles.css", path.join(vaultPluginDir, "styles.css"));
	}
	console.log(`Successfully deployed plugin files to ${vaultPluginDir}`);
	process.exit(0);
} else {
	await context.watch();
}
