import { build } from 'esbuild';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
const out = 'output/playwright'; fs.mkdirSync(out, { recursive: true });
await build({ entryPoints: ['tests/preview.ts'], bundle: true, outfile: `${out}/preview.js`, alias: { obsidian: path.resolve('tests/obsidian-preview.ts') } });
const host = `
:root { --background-primary:#fff; --background-secondary:#f5f5f7; --background-modifier-border:#e1e1e6; --text-normal:#25252c; --text-muted:#61616c; --text-accent:#6553b8; --interactive-accent:#705dc8; --text-on-accent:#fff; --text-error:#bc3434; --font-ui-small:13px; --font-monospace:ui-monospace,monospace; }
body.dark { --background-primary:#242429; --background-secondary:#2d2d34; --background-modifier-border:#474750; --text-normal:#ededf1; --text-muted:#b0b0bc; --text-accent:#b3a3ff; --interactive-accent:#7e68d4; --text-error:#ff9999; }
* { box-sizing:border-box; } body { margin:0; background:var(--background-secondary); color:var(--text-normal); font-family:Segoe UI,Microsoft YaHei,sans-serif; font-size:14px; } nav { display:flex; gap:8px; flex-wrap:wrap; padding:16px; } button, input, select { font:inherit; color:var(--text-normal); background:var(--background-primary); border:1px solid var(--background-modifier-border); border-radius:5px; padding:6px 10px; } button { cursor:pointer; } button:disabled { opacity:.5; cursor:default; } .mod-cta { background:var(--interactive-accent); border-color:var(--interactive-accent); color:var(--text-on-accent); } #surface { margin:12px auto 40px; max-width:740px; } .modal, .jev-settings-container { background:var(--background-primary); padding:28px; border:1px solid var(--background-modifier-border); border-radius:14px; margin:auto; } .setting-item { display:flex; align-items:center; justify-content:space-between; padding:16px 0; border-bottom:1px solid var(--background-modifier-border); gap:16px; } .setting-item-info { flex:1; } .setting-item-name { font-size:13px; font-weight:500; } .setting-item-description { color:var(--text-muted); font-size:12px; line-height:1.5; margin-top:4px; } .setting-item-control { display:flex; align-items:center; gap:8px; min-width:0; } .setting-item-heading { border-bottom:0; margin-top:14px; } .setting-item-heading .setting-item-name { font-weight:650; font-size:15px; } #notice { padding:0 16px 16px; font-size:12px; color:var(--text-muted); } input[type=checkbox] { accent-color:var(--interactive-accent); } @media(max-width:600px) { .modal,.jev-settings-container { padding:18px; } #surface { max-width:calc(100vw - 24px); } }
`;
const html = `<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Smart Tagger · Synthetic UI preview</title><style>${host}</style><link rel="stylesheet" href="/styles.css"><body><nav><button data-view="batch">批量分类</button><button data-view="note">笔记推荐</button><button data-view="settings">设置</button><button id="theme">明暗主题</button><button id="language">中文 / English</button></nav><div id="surface"></div><div id="notice">模拟数据预览 · 不访问真实笔记或 API</div><script src="/preview.js"></script></body></html>`;
const server = http.createServer((req, res) => {
 if (req.url === '/styles.css') { res.setHeader('Content-Type','text/css'); res.end(fs.readFileSync('styles.css')); }
 else if (req.url === '/preview.js') { res.setHeader('Content-Type','application/javascript'); res.end(fs.readFileSync(`${out}/preview.js`)); }
 else { res.setHeader('Content-Type','text/html; charset=utf-8'); res.end(html); }
});
server.listen(4178, '127.0.0.1', () => console.log('Synthetic preview: http://127.0.0.1:4178'));
